/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversormonedas;

import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ASUS VIVOBOOK
 */
public class VentanaConversorDivisas extends javax.swing.JFrame {

    private DefaultComboBoxModel<Moneda> modelo = new DefaultComboBoxModel();
    private DefaultComboBoxModel<Moneda> modelo1 = new DefaultComboBoxModel();
    private Conversor divisas;
    private DecimalFormat formato = new DecimalFormat("#.##");

    /**
     * Creates new form VentanaMenuPrincipal
     */
    public VentanaConversorDivisas() {
        llenarComboBox();
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        TextPrompt textoPlaceholder = new TextPrompt("0.00", fieldMonto);
        divisas = new Conversor(obtenerAbreviacion(comboMonedaFrom), obtenerAbreviacion(comboMonedaTo));
    }

    public void llenarComboBox() {
        añadirElementos(new Moneda("USD", "Estados Unidos"));
        añadirElementos(new Moneda("EUR", "Europa"));
        añadirElementos(new Moneda("COP", "Colombia"));
        añadirElementos(new Moneda("CLP", "Chile"));
        añadirElementos(new Moneda("ARS", "Argentina"));
        añadirElementos(new Moneda("PEN", "Peru"));

    }

    public void añadirElementos(Moneda moneda) {
        modelo.addElement(moneda);
        modelo1.addElement(moneda);
    }

    public void obtenerConversion() {
        if (!fieldMonto.getText().isEmpty())
        {
            try
            {
                String resultado = formato.format(divisas.getValor() * Double.parseDouble(fieldMonto.getText()));
                fieldResultado.setText(String.valueOf(resultado));
            } catch (NumberFormatException ex)
            {
                mensajeError();
            }
        } else
        {
            fieldResultado.setText("");
        }

    }

    public String obtenerAbreviacion(JComboBox<Moneda> comboMoneda) {
        return ((Moneda) comboMoneda.getSelectedItem()).getAbreviacion();
    }

    public void mensajeError() {
        JOptionPane.showMessageDialog(null, "Solo se aceptan numeros", "Error", JOptionPane.ERROR_MESSAGE, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jComboBox1 = new javax.swing.JComboBox<>();
        panel = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        fieldMonto = new javax.swing.JTextField();
        labelTipoCambio = new javax.swing.JLabel();
        comboMonedaFrom = new javax.swing.JComboBox<>();
        comboMonedaTo = new javax.swing.JComboBox<>();
        labelResultado = new javax.swing.JLabel();
        fieldResultado = new javax.swing.JTextField();
        labelFrom = new javax.swing.JLabel();
        labelTo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        itemDivisas = new javax.swing.JMenuItem();
        itemTemperaturas = new javax.swing.JMenuItem();
        itemCerrar = new javax.swing.JMenuItem();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(new java.awt.GridBagLayout());

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("CONVERSOR DE DIVISAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 30, 0);
        panel.add(labelTitulo, gridBagConstraints);

        labelCantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCantidad.setText("Cantidad a convertir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(9, 10, 10, 10);
        panel.add(labelCantidad, gridBagConstraints);

        fieldMonto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldMontoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 100, 10, 100);
        panel.add(fieldMonto, gridBagConstraints);

        labelTipoCambio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTipoCambio.setText("Seleccione el tipo de cambio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(9, 10, 10, 10);
        panel.add(labelTipoCambio, gridBagConstraints);

        comboMonedaFrom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboMonedaFrom.setModel(modelo);
        comboMonedaFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMonedaFromActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 130);
        panel.add(comboMonedaFrom, gridBagConstraints);

        comboMonedaTo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboMonedaTo.setModel(modelo1);
        comboMonedaTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMonedaToActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 130);
        panel.add(comboMonedaTo, gridBagConstraints);

        labelResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelResultado.setText("Resultado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(9, 10, 10, 10);
        panel.add(labelResultado, gridBagConstraints);

        fieldResultado.setEditable(false);
        fieldResultado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 100, 30, 100);
        panel.add(fieldResultado, gridBagConstraints);

        labelFrom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelFrom.setText("De:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 10, 0);
        panel.add(labelFrom, gridBagConstraints);

        labelTo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTo.setText("A:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 10, 0);
        panel.add(labelTo, gridBagConstraints);

        menu.setText("Menu");
        menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemDivisas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemDivisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cambio-de-divisas.png"))); // NOI18N
        itemDivisas.setText("Conversor de divisas");
        menu.add(itemDivisas);

        itemTemperaturas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemTemperaturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/temperatura.png"))); // NOI18N
        itemTemperaturas.setText("Conversor de temperaturas");
        itemTemperaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTemperaturasActionPerformed(evt);
            }
        });
        menu.add(itemTemperaturas);

        itemCerrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        itemCerrar.setText("Cerrar");
        itemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarActionPerformed(evt);
            }
        });
        menu.add(itemCerrar);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemCerrarActionPerformed

    private void fieldMontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldMontoKeyReleased
        obtenerConversion();
    }//GEN-LAST:event_fieldMontoKeyReleased

    private void comboMonedaFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMonedaFromActionPerformed
        divisas.setTipoFrom(obtenerAbreviacion(comboMonedaFrom));
        divisas.obtenerDivisas();
        obtenerConversion();
    }//GEN-LAST:event_comboMonedaFromActionPerformed

    private void comboMonedaToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMonedaToActionPerformed
        divisas.setTipoTo(obtenerAbreviacion(comboMonedaTo));
        divisas.obtenerDivisas();
        obtenerConversion();
    }//GEN-LAST:event_comboMonedaToActionPerformed

    private void itemTemperaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTemperaturasActionPerformed
        dispose();
        VentanaConversorTemperatura vt = new VentanaConversorTemperatura();
    }//GEN-LAST:event_itemTemperaturasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try
        {
            UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
        } catch (ClassNotFoundException ex)
        {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            // Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex)
        {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConversorDivisas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<conversormonedas.Moneda> comboMonedaFrom;
    private javax.swing.JComboBox<conversormonedas.Moneda> comboMonedaTo;
    private javax.swing.JTextField fieldMonto;
    private javax.swing.JTextField fieldResultado;
    private javax.swing.JMenuItem itemCerrar;
    private javax.swing.JMenuItem itemDivisas;
    private javax.swing.JMenuItem itemTemperaturas;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelFrom;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JLabel labelTipoCambio;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTo;
    private javax.swing.JMenu menu;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
